name: flet_painter
description: Flet FletPainter control
repository: https://github.com/Wanna-Pizza/flet-painter/src/flutter/flet_painter
version: 0.1.0
homepage: https://github.com/Wanna-Pizza/flet-painter

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flet:
    git:
      url: https://github.com/flet-dev/flet.git
      path: packages/flet
      ref: v1
  flutter:
    sdk: flutter
  # flutter_painter_v2: ^2.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
